************* Module credit-risk-models.pd.pd_validator_engine
pd/pd_validator_engine.py:29:27: C0103: Argument name "X" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:29:30: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:32:8: C0103: Variable name "cm" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:44:30: C0103: Argument name "X" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:44:33: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:46:18: W0612: Unused variable 'thresholds' (unused-variable)
pd/pd_validator_engine.py:70:29: C0103: Argument name "X" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:70:32: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:72:27: W0612: Unused variable 'thresholds' (unused-variable)
pd/pd_validator_engine.py:87:27: C0103: Argument name "X_test" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:112:37: C0103: Argument name "X_train" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:113:13: C0103: Variable name "ax" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:112:37: W0613: Unused argument 'X_train' (unused-argument)
pd/pd_validator_engine.py:112:46: W0613: Unused argument 'y_train' (unused-argument)
pd/pd_validator_engine.py:113:8: W0612: Unused variable 'fig' (unused-variable)
pd/pd_validator_engine.py:120:42: C0103: Argument name "X" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:120:45: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:127:21: C0103: Variable name "ax" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:120:45: W0613: Unused argument 'y' (unused-argument)
pd/pd_validator_engine.py:125:8: W0612: Unused variable 'fig' (unused-variable)
pd/pd_validator_engine.py:138:42: C0103: Argument name "X" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:138:45: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:160:13: C0103: Variable name "ax" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:160:8: W0612: Unused variable 'fig' (unused-variable)
pd/pd_validator_engine.py:176:30: C0103: Argument name "X_train" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:189:29: C0103: Argument name "X_test" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:197:27: C0103: Argument name "X" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:197:29: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:207:32: C0103: Argument name "X" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:271:8: C0103: Argument name "X_train" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:272:8: C0103: Argument name "X_train_woe" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:273:8: C0103: Argument name "X_test" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:274:8: C0103: Argument name "X_test_woe" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:285:12: C0103: Variable name "X_train_model" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:286:12: C0103: Variable name "X_test_model" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:289:12: C0103: Variable name "X_val_model" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:293:16: C0103: Variable name "X_train_model" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:298:16: C0103: Variable name "X_test_model" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:305:16: C0103: Variable name "X_val" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:306:16: C0103: Variable name "X_val_model" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:308:16: C0103: Variable name "X_val_model" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:321:16: C0103: Variable name "X_train_model" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:324:16: C0103: Variable name "X_test_model" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:339:16: C0103: Variable name "X_train_model" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:340:16: C0103: Variable name "X_test_model" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:343:16: C0103: Variable name "X_val" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:345:16: C0103: Variable name "X_val_model" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:353:16: C0103: Variable name "X_val_model" doesn't conform to snake_case naming style (invalid-name)
pd/pd_validator_engine.py:281:38: W0612: Unused variable 'scaler' (unused-variable)

------------------------------------------------------------------
Your code has been rated at 8.22/10 (previous run: 8.12/10, +0.10)

